// Tracks
export const TRACK_CHANGED = "TRACK_CHANGED";

// Auth
export const ACCESS_TOKEN_REQUEST = "ACCESS_TOKEN_REQUEST";
export const ACCESS_TOKEN_SUCCESS = "ACCESS_TOKEN_SUCCESS";
export const ACCESS_TOKEN_FAILURE = "ACCESS_TOKEN_FAILURE";
