// Tracks
export const TRACK_REQUEST = "TRACK_REQUEST";
export const TRACK_CHANGED = "TRACK_CHANGED";
export const TRACK_UPDATED = "TRACK_UPDATED";
export const TRACK_FAILURE = "TRACK_FAILURE";

// Auth
export const ACCESS_TOKEN_REQUEST = "ACCESS_TOKEN_REQUEST";
export const ACCESS_TOKEN_SUCCESS = "ACCESS_TOKEN_SUCCESS";
export const ACCESS_TOKEN_FAILURE = "ACCESS_TOKEN_FAILURE";
export const REFRESH_TOKEN_REQUEST = "REFRESH_TOKEN_REQUEST";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAILURE = "REFRESH_TOKEN_FAILURE";
