// Tracks
export const TRACK_REQUEST = "TRACK_REQUEST";
export const TRACK_REQUEST_SUCCESS = "TRACK_REQUEST_SUCCESS";
export const TRACK_REQUEST_FAILURE = "TRACK_REQUEST_FAILURE";
export const TRACK_CHANGED = "TRACK_CHANGED";

// Auth
export const ACCESS_TOKEN_REQUEST = "ACCESS_TOKEN_REQUEST";
export const ACCESS_TOKEN_SUCCESS = "ACCESS_TOKEN_SUCCESS";
export const ACCESS_TOKEN_FAILURE = "ACCESS_TOKEN_FAILURE";
export const ACCESS_TOKEN_REFRESHED = "ACCESS_TOKEN_REFRESHED";